# Reference: https://golangci-lint.run/usage/configuration/

version: "2"

linters:
  default: none
  enable:
    - errcheck
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    gocritic:
      disabled-checks:
        - singleCaseSwitch
  exclusions:
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
        text: Error return value of `d.Set` is not checked

formatters:
  enable:
    - gci
    - gofmt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/hypnoglow/terraform-provider-oryhydra)

issues:
  fix: true

run:
  timeout: 5m
  build-tags: []
