run:
  concurrency: 4
  timeout: 5m

linters:
  disable-all: true
  enable:
    - deadcode
    - depguard
    - errcheck
    - gci
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - maligned
    - misspell
    - nakedret
    # - prealloc
    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck

linters-settings:
  goimports:
    local-prefixes: github.com/hypnoglow/terraform-provider-oryhydra

issues:
  exclude-rules:
    - linters:
        - errcheck
      text: Error return value of `d.Set` is not checked
    - linters:
        - gocritic
      text: ^singleCaseSwitch
